### PR TITLE
restore DIM that was lost between 0.7.9 and 0.8.1

### PR DESCRIPTION
**Pull request by narc-Ontakac2**
It seems DIM was lost 8 years ago. Since I can see no reason for its removal I think it was accidential. At the same time there was a change affecting DIMS.

### CODE REVIEW

**Comment by narc-Ontakac2** [comment]
This depends on PR #9.

**Comment by fingolfin** [comment]
Huh, this PR seems to have identical content as PR #9 (which I just merged via squash) ?

**Comment by narc-Ontakac2** [comment]
That was a git accident. It seems a rebase followed by a push -f did not exactly do what I expected. I just fixed it.

**Comment by fingolfin** [comment]
Thanks!

**Pull request merged**
